// This file is auto-generated by Payload when you run `payload generate:importmap`.
// Do not edit manually.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const importMap: Record<string, any> = {}
